import Project.ConnectionProvider;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class instructionStudent extends javax.swing.JFrame {
    public String rollNo;
    /**
     * Creates new form instructionStudent
     */
    public instructionStudent() {
        initComponents();
    }

    public instructionStudent(String rollNo1) {
        initComponents();
        rollNo = rollNo1;
        jLabel_rollNo.setText(rollNo);
        byte[] image = null;
        jDateChooser_dob.setDateFormatString("dd-MM-yyyy");
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, 
                        ResultSet.CONCUR_UPDATABLE);//Notice, this line may be throw sql exception 
            ResultSet rs = st.executeQuery("select avatar, name, marks, password, dob, gender, contactNo, email, address from user where rollNo = '"+rollNo+"'");
            
            while(rs.next()){
                image = rs.getBytes(1);
                Image img = Toolkit.getDefaultToolkit().createImage(image).getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                jLabel_avatar.setIcon(icon);
                jLabel_name.setText(rs.getString(2));
                jTextField_Name.setText(rs.getString(2));
                jLabel_marks.setText(String.valueOf(rs.getInt(3)));
                jPasswordField_password.setText(rs.getString(4));
                String format_dob = rs.getString(5).substring(8) + "-"+rs.getString(5).substring(5,7)+"-"+rs.getString(5).substring(0,4);
                jDateChooser_dob.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(format_dob));
                jComboBox_gender.setSelectedItem(rs.getString(6));
                jTextField_contact.setText(rs.getString(7));
                jTextField_email.setText(rs.getString(8));
                jTextField_address.setText(rs.getString(9));
            }
            jTextField_Name.setEnabled(false);
            jPasswordField_password.setEnabled(false);
            jDateChooser_dob.setEnabled(false);
            jComboBox_gender.setEnabled(false);
            jTextField_contact.setEnabled(false);
            jTextField_email.setEnabled(false);
            jTextField_address.setEnabled(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_avatar = new javax.swing.JLabel();
        jLabel_rollNo = new javax.swing.JLabel();
        jLabel_marks = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jCheckBox_showPass = new javax.swing.JCheckBox();
        jTextField_Name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser_dob = new com.toedter.calendar.JDateChooser();
        jTextField_address = new javax.swing.JTextField();
        jTextField_contact = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_start = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_exit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_exit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_32.png"))); // NOI18N
        jButton_exit.setBorder(null);
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Personal Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Roll Number:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Current Marks:");

        jLabel_name.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(0, 255, 0));
        jLabel_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_name.setText("Henry");

        jLabel_avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_icon_150.png"))); // NOI18N
        jLabel_avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_avatarMouseClicked(evt);
            }
        });

        jLabel_rollNo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_rollNo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_rollNo.setText("10000");

        jLabel_marks.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_marks.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_marks.setText("00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_marks)
                    .addComponent(jLabel_rollNo))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel_name)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel_rollNo))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel_marks))
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 770));

        jPasswordField_password.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPasswordField_password.setText("jPasswordField1");
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 260, -1));

        jCheckBox_showPass.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox_showPass.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jCheckBox_showPass.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBox_showPass.setText("Show / Hide");
        jCheckBox_showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_showPassActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox_showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, -1, -1));

        jTextField_Name.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 424, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        jDateChooser_dob.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jDateChooser_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 200, 30));

        jTextField_address.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jTextField_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 780, -1));

        jTextField_contact.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jTextField_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 424, -1));

        jTextField_email.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 780, -1));

        jComboBox_gender.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(jComboBox_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 200, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("Address:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setText("Password");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Contact Number:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Date of Birth:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jButton_start.setBackground(new java.awt.Color(0, 51, 204));
        jButton_start.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jButton_start.setForeground(new java.awt.Color(255, 255, 255));
        jButton_start.setText("START QUIZ");
        jButton_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 680, -1, -1));

        jButton_clear.setBackground(new java.awt.Color(0, 51, 204));
        jButton_clear.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jButton_clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_clear.setText("CLEAR");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, -1, -1));

        jButton_update.setBackground(new java.awt.Color(0, 51, 204));
        jButton_update.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("UPDATE");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 680, -1, -1));

        jButton_save.setBackground(new java.awt.Color(0, 51, 204));
        jButton_save.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jButton_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton_save.setText("SAVE");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 680, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_startActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new quizExamStudent(rollNo).setVisible(true);
    }//GEN-LAST:event_jButton_startActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton_exitActionPerformed

    private void jCheckBox_showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_showPassActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_showPass.isSelected()){
            jPasswordField_password.setEchoChar((char)0);
        }
        else{
            jPasswordField_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_showPassActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:        
        String name = jTextField_Name.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dob = sdf.format(jDateChooser_dob.getDate());
        String gender = String.valueOf(jComboBox_gender.getSelectedItem());
        String contactNo = jTextField_contact.getText();
        String email = jTextField_email.getText();
        String address = jTextField_address.getText();
        String password = jPasswordField_password.getText();
        ImageIcon icon_avatar = (ImageIcon) jLabel_avatar.getIcon();
        BufferedImage bi = new BufferedImage(icon_avatar.getIconWidth(), 
                    icon_avatar.getIconWidth(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D bGr = bi.createGraphics();
        bGr.drawImage(icon_avatar.getImage(), 0, 0, null);
        bGr.dispose();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        
        try {
            ImageIO.write(bi, "png", baos);
            byte[] byteArray = baos.toByteArray();
            
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("update user set name = ?,dob = ?,gender = ?, contactNo = ?,email = ?,address = ?,password = ?,avatar = ? where rollNo = ?");
            ps.setString(1, name);
            ps.setString(2, dob);
            ps.setString(3, gender);
            ps.setString(4, contactNo);
            ps.setString(5, email);
            ps.setString(6, address);
            ps.setString(7, password);
            ps.setBytes(8, byteArray);
            ps.setString(9, rollNo);
            ps.executeUpdate();
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, "Successfully Registered!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        jTextField_Name.setEnabled(true);
        jPasswordField_password.setEnabled(true);
        jDateChooser_dob.setEnabled(true);
        jComboBox_gender.setEnabled(true);
        jTextField_contact.setEnabled(true);
        jTextField_email.setEnabled(true);
        jTextField_address.setEnabled(true);
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jLabel_avatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_avatarMouseClicked
        // TODO add your handling code here:
        JFileChooser picchooser = new JFileChooser();
        picchooser.setDialogTitle("Select Image");
        picchooser.showOpenDialog(null);
        File pic = picchooser.getSelectedFile();
        String path = pic.getAbsolutePath();
        ImageIcon picture = new ImageIcon(path);
        Image image = picture.getImage(); // transform it 
        Image newimg = image.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        picture = new ImageIcon(newimg);
        jLabel_avatar.setIcon(picture);
    }//GEN-LAST:event_jLabel_avatarMouseClicked

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        jTextField_Name.setText("");
        jPasswordField_password.setText("");
        jTextField_contact.setText("");
        jTextField_email.setText("");
        jTextField_address.setText("");
    }//GEN-LAST:event_jButton_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instructionStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_start;
    private javax.swing.JButton jButton_update;
    private javax.swing.JCheckBox jCheckBox_showPass;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private com.toedter.calendar.JDateChooser jDateChooser_dob;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_avatar;
    private javax.swing.JLabel jLabel_marks;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_rollNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_contact;
    private javax.swing.JTextField jTextField_email;
    // End of variables declaration//GEN-END:variables
}
