import java.sql.*;
import Project.ConnectionProvider;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.*;
import java.util.Date;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

public class studentDetails extends javax.swing.JFrame {
    FileInputStream avatar;
    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel_Time.setText(dFormat.format(date));
        
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);//Notice, this line may be throw sql exception 
            ResultSet rs = st.executeQuery("select rollNo from user order by rollNo DESC LIMIT 1");
            while(rs.next()){
                int id = Integer.parseInt(rs.getString(1))+1;//gán id tự động cho question
                jLabel_rollNo.setText(String.valueOf(id));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_contact = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jLabel_avatar = new javax.swing.JLabel();
        jDateChooser_dob = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jCheckBox_showPass = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Time = new javax.swing.JLabel();
        jButton_Save_Next = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jLabel_rollNo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/index student.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("Fill Up The Form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 17, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 1366, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Roll Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Date of Birth:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Gender:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Contact Number:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Email:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Address:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, -1, -1));

        jTextField_Name.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 424, -1));

        jTextField_contact.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(jTextField_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 424, -1));

        jTextField_email.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 985, -1));

        jTextField_address.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(jTextField_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 985, -1));

        jComboBox_gender.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(jComboBox_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 200, -1));

        jLabel_avatar.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/male-avatar.png"))); // NOI18N
        jLabel_avatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 3));
        jLabel_avatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_avatarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 290, 290));

        jDateChooser_dob.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(jDateChooser_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("Password");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jPasswordField_password.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPasswordField_password.setText("jPasswordField1");
        getContentPane().add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 260, -1));

        jCheckBox_showPass.setBackground(new java.awt.Color(204, 204, 255));
        jCheckBox_showPass.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jCheckBox_showPass.setForeground(new java.awt.Color(255, 102, 0));
        jCheckBox_showPass.setText("Show / Hide");
        jCheckBox_showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_showPassActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(230, 230, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel_Time.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_Time.setForeground(new java.awt.Color(51, 0, 204));
        jPanel1.add(jLabel_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 160, 30));

        jButton_Save_Next.setBackground(new java.awt.Color(0, 153, 51));
        jButton_Save_Next.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton_Save_Next.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Save_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton_Save_Next.setText("SAVE");
        jButton_Save_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Save_NextActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Save_Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, -1, 40));

        jButton_Exit.setBackground(new java.awt.Color(230, 230, 255));
        jButton_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_32.png"))); // NOI18N
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, -1, -1));

        jLabel_rollNo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_rollNo.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_rollNo.setText("10000");
        jPanel1.add(jLabel_rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>                        

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }
    }                                            

    private void jButton_Save_NextActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        String rollNo = jLabel_rollNo.getText();
        String name = jTextField_Name.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dob = sdf.format(jDateChooser_dob.getDate());
        String gender = String.valueOf(jComboBox_gender.getSelectedItem());
        String contactNo = jTextField_contact.getText();
        String email = jTextField_email.getText();
        String address = jTextField_address.getText();
        String marks = "0";
        String password = jPasswordField_password.getText();
        ImageIcon icon_avatar = (ImageIcon) jLabel_avatar.getIcon();
        BufferedImage bi = new BufferedImage(icon_avatar.getIconWidth(), 
                    icon_avatar.getIconWidth(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D bGr = bi.createGraphics();
        bGr.drawImage(icon_avatar.getImage(), 0, 0, null);
        bGr.dispose();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        
        try {
            //chuyển ảnh thàng mảng Byte để lưu vào CSDL
            ImageIO.write(bi, "png", baos);
            byte[] byteArray = baos.toByteArray();
            
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into user values(?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, rollNo);
            ps.setString(2, name);
            ps.setString(3, dob);
            ps.setString(4, gender);
            ps.setString(5, contactNo);
            ps.setString(6, email);
            ps.setString(7, address);
            ps.setString(8, marks);
            ps.setString(9, password);
            ps.setInt(10, 0);
            ps.setBytes(11, byteArray);
            ps.executeUpdate();
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, "Successfully Registered!");
            setVisible(false);
            new instructionStudent(rollNo).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }                                                 

    private void jLabel_avatarMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        JFileChooser picchooser = new JFileChooser();
        picchooser.setDialogTitle("Select Image");
        picchooser.showOpenDialog(null);
        File pic = picchooser.getSelectedFile();
        String path = pic.getAbsolutePath();
        ImageIcon picture = new ImageIcon(path);
        Image image = picture.getImage(); // transform it 
        Image newimg = image.getScaledInstance(280, 280, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        picture = new ImageIcon(newimg);
       
        jLabel_avatar.setIcon(picture);
    }                                          

    private void jCheckBox_showPassActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        //Hiển thị hoặc ẩn password
        if(jCheckBox_showPass.isSelected()){
            jPasswordField_password.setEchoChar((char)0);
        }
        else{
            jPasswordField_password.setEchoChar('*');
        }
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Save_Next;
    private javax.swing.JCheckBox jCheckBox_showPass;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private com.toedter.calendar.JDateChooser jDateChooser_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Time;
    private javax.swing.JLabel jLabel_avatar;
    private javax.swing.JLabel jLabel_rollNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_contact;
    private javax.swing.JTextField jTextField_email;
    // End of variables declaration                   
}
