import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class successfullySubmited extends javax.swing.JFrame {
    public String rollNo;
    /**
     * Creates new form successfullySubmited
     */
    public successfullySubmited() {
        initComponents();
    }
    
    public successfullySubmited(String marks, String rollNo, String name) {
        initComponents();
        String marks1 = "Marks Obtained: " + marks;
        jLabel1.setText(marks1);
        this.rollNo = rollNo;
        if(Integer.parseInt(marks) >= 8){
            ImageIcon icon = new ImageIcon(getClass().getResource("/ezgif.com-gif-maker (1).gif"));
            jLabel_high_result.setIcon(icon);
            jLabel_name.setText("Congratulation, "+name+"!");
        }
        else{
            ImageIcon icon = new ImageIcon(getClass().getResource("/sadness.png"));
            jLabel_low_result.setIcon(icon);
            jLabel_name.setText("<html>"+name + ", you need more <br>practice!</html>");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jButton_restart = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();
        jLabel_high_result = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_low_result = new javax.swing.JLabel();
        jButton_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Marks Obtained: 10");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel_name.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel_name.setText("Successfully Updated");
        getContentPane().add(jLabel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jButton_restart.setBackground(new java.awt.Color(0, 153, 51));
        jButton_restart.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton_restart.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restart.setText("RESTART");
        jButton_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restartActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, -1, -1));

        jButton_logout.setBackground(new java.awt.Color(0, 153, 51));
        jButton_logout.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton_logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logout.setText("LOG OUT");
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, -1, -1));
        getContentPane().add(jLabel_high_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 700, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel_low_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 150, 150));

        jButton_exit.setBackground(new java.awt.Color(204, 204, 255));
        jButton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_32.png"))); // NOI18N
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton_exitActionPerformed

    private void jButton_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restartActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new quizExamStudent(rollNo).setVisible(true);
    }//GEN-LAST:event_jButton_restartActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(successfullySubmited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(successfullySubmited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(successfullySubmited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(successfullySubmited.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new successfullySubmited().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_restart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_high_result;
    private javax.swing.JLabel jLabel_low_result;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
